# Generated by Django 4.1.4 on 2023-03-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="variation_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="variation",
            old_name="variation_value",
            new_name="value",
        ),
    ]
