# Generated by Django 4.1.7 on 2023-03-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
