# Generated by Django 4.1.7 on 2023-03-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_variation_category_variation_category_and_more"),
        ("orders", "0003_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
